
/**************************************************************
 *	
 *	yeah, 8 bit, 11025Hz,
 *	1 channel, 5781 bytes/channel
 *	Total Size: 1 * 5781 + 4 (header) = 5825 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/kathleentynan/Documents/Spring2017/CS2261/BitmojiJump/yeah.wav
 *	Time-stamp: Tue Apr 11 22:08:17 2017
 *	
 **************************************************************/

#ifndef __SONGSH__
#define __SONGSH__

#define YEAHFREQ 11025
#define YEAHLEN 5781

#define HAPPYFREQ 11025
#define HAPPYLEN 350754

#define JUMPFREQ 11025
#define JUMPLEN 3308

#define INTROSONGFREQ 11025
#define INTROSONGLEN 194316

extern const unsigned char introsong[194316]; 
extern const unsigned char yeah[5781];
extern const unsigned char happy[350754];
extern const unsigned char jump[3308];

#endif /* __SONGSH__ */
